config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  resources :users, only: [:new, :show, :create]
  resources :bands, only: [:index, :new, :create, :edit, :show, :update, :destroy] do
    resources :albums, only: [:index, :new, :create, :edit, :update, :show, :destroy]
  end
  resource :session, only: [:create, :destroy, :new]
  
end

app/models/album.rb
class Album < ApplicationRecord
  validates :title, :year, :in_studio, presence:true

  belongs_to(
    :band,
    class_name: :Band,
    foreign_key: :band_id,
    primary_key: :id
  )

  has_many(
    :tracks,
    class_name: :Track,
    foreign_key: :track_id,
    primary_key: :id
  )

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord
  validates :name, presence: :true

  has_many(
    :albums,
    class_name: :Album,
    foreign_key: :band_id,
    primary_key: :id,
    dependent: :delete_all
  )

  def inspect
    self.name
  end
end

app/models/track.rb
class Track < ApplicationRecord
  validates :title, :ord, presence:true

  belongs_to(
    :album,
    class_name: :Album,
    foreign_key: :album_id,
    primary_key: :id
  )

  belongs_to :band, through: :album, source: :band
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :password_digest, :session_token, presence: :true
  after_initialize :ensure_session_token
  attr_reader :password

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(email)
    User.find_by(email: email)
  end

  private
  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController


  before_action :require_login


  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.band_id = params[:band_id]
    if @album.save!
      redirect_to band_albums_url(@album.band_id)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def show
    @album = Album.find(params[:item][:band_id])
  end

  def index
    @band = Band.find(params[:band_id])
    @albums = @band.albums
  end

  def update
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
    redirect_to band_albums_url(@album.band_id)
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :in_studio, :band_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def logged_in?
    !!current_user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

end

app/controllers/bands_controller.rb
class BandsController < ApplicationController

  before_action :require_login

  def index
    @bands = Band.all
  end

  def create
    @band = Band.new(bands_params)
    if @band.save!
      redirect_to bands_url
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def new
    @band = Band.new
  end

  def edit
    @band = Band.find(params[:id])
  end

  def show
    @band = Band.find(params[:id])
  end

  def update
    @band = Band.find(params[:id])
    if @band.update_attributes(bands_params)
      redirect_to bands_url
    else 
      flash.now[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  def destroy
    @band = Band.find(params[:id])
    if @band.destroy
      redirect_to bands_url
    else 
      flash.now[:errors] = @band.errors.full_messages
      redirect_to bands_url
    end
  end

  def bands_params
    params.require(:band).permit(:name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params[:user][:email])
    if user
      login(user)
      redirect_to :bands
    else 
      flash.now[:errors] = "Incorrect username or password"
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  def new
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    
  end

  def create
    @user = User.new(user_params)
    if @user.save!
      login(@user)
      redirect_to :bands
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to :new
    end
  end

  def show
    @user = User.find_by(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_form.html.erb
<% if type == :new %>
<% action = band_albums_url%>
<% button_text = "Create New Album" %>
<% else %>
<% action = band_album_url(album) %>
<% button_text = "Update Album" %>
<% end %>

<form action="<%=action%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch" />
  <% end %>

  <% if type == :destroy %>
    <input type="hidden" name="_method" value="delete" />
  <% end %>
  
  <label> Title
    <input type="text" name="album[title]" value="<%= album.title %>">
  </label>
  <label> Date (Y-M-D)
    <input type="text" name="album[year]" value="<%= album.year %>">
  </label>
  <label> Live?
    <input type="checkbox" name="album[in_studio]" value="<%= album.in_studio %>">
  </label>    

  <input type="submit" value="<%= button_text %>">
</form>

app/views/albums/_list.html.erb
<li> 

  <%= item.inspect %>
  </br>
  
</li>
  <form id="delete_album" action="<%= "albums/#{item.id}" %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
    <input type="hidden" name="_method" value="delete" />
    <input type="submit" value="Delete">
  </form>
  

app/views/albums/create.html.erb
<h1>Albums#create</h1>
<p>Find me in app/views/albums/create.html.erb</p>

app/views/albums/destroy.html.erb
<h1>Albums#destroy</h1>
<p>Find me in app/views/albums/destroy.html.erb</p>

app/views/albums/edit.html.erb
<h1>Albums#edit</h1>
<p>Find me in app/views/albums/edit.html.erb</p>

app/views/albums/index.html.erb
<h2>Band's Album List</h2>

<ul>
<%= render partial: 'list', :collection => @albums, as: :item %>
</ul>

<a href="<%=new_band_album_url%>"> Create New Album </a>

app/views/albums/new.html.erb
<h2>New Album</h2>

<%= render 'form', type: :new, album: @album  %>

app/views/albums/show.html.erb
<h1>Albums#show</h1>
<p>Find me in app/views/albums/show.html.erb</p>

app/views/albums/update.html.erb
<h1>Albums#update</h1>
<p>Find me in app/views/albums/update.html.erb</p>

app/views/bands/_form.html.erb
<% if type == :new %>
<% action = bands_url%>
<% button_text = "Create New Band" %>
<% else %>
<% action = band_url(band) %>
<% button_text = "Update Band" %>
<% end %>

<form action="<%=action%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  
  <% if type == :edit %>
    <input type="hidden" name="_method" value="patch" />
  <% end %>

  <% if type == :destroy %>
    <input type="hidden" name="_method" value="delete" />
  <% end %>
  
  
  <label> Name
    <input type="text" name="band[name]" value="<%= band.name %>">
  </label>
  <input type="submit" value="<%= button_text %>">
</form>

app/views/bands/_list.html.erb
<li><a href="<%=band_albums_url(item)%>"> <%= item.inspect %> </a>

<form id="update_band" action="<%="bands/#{item.id}"%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="hidden" name="_method" value="patch" />
  <label> Band Name
    <input type="text" name="band[name]" value="<%= item.name %>">
  </label>
  <input type="submit" value="Update">
</form>
<form id="destroy_band" action="<%="/bands/#{item.id}"%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <input type="hidden" name="_method" value="delete" />
  <input type="submit" value="Delete">
</form>
</li>

app/views/bands/create.html.erb
<h1>Bands#create</h1>
<p>Find me in app/views/bands/create.html.erb</p>

app/views/bands/destroy.html.erb
<h1>Bands#destroy</h1>
<p>Find me in app/views/bands/destroy.html.erb</p>

app/views/bands/edit.html.erb
<h1>Bands#edit</h1>

<%= render 'form', type: :edit, band: @band  %>

app/views/bands/index.html.erb
<h2>Bands</h2>

<ul>
<%= render partial: 'list', :collection => @bands, as: :item %>
</ul>

<a href="<%=new_band_url%>"> Create New Band </a>

app/views/bands/new.html.erb
<h2>New Band</h2>

<%= render 'form', type: :new, band: @band  %>

app/views/bands/show.html.erb
<h1>Bands#show</h1>
<p>Find me in app/views/bands/show.html.erb</p>

app/views/bands/update.html.erb
<h1>Bands#update</h1>
<p>Find me in app/views/bands/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   
   
   <% if logged_in? %>
      <%= current_user.email %>
      <form id="logout_session" action="<%=session_url%>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
        <input type="hidden" name="_method" value="delete" />
        <input type="submit" value="Sign Out">
      </form>
   <% else %>
     <a href="<%=new_session_url%>"> Sign In </a>
     </br>
     <a href="<%=new_user_url%>"> Sign Up </a>
   <% end %>

  <% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |err| %>
    <li><%= err %></li>
    <% end %>
  </ul>     
  <% end %>
   
   
    <%= yield %>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form id="create_user" action="<%=users_url%>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" />
  <label> Email
    <input type="text" name="user[email]">
  </label>
  <label> Password
    <input type="text" name="user[password]">
  </label>  
  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>